// <auto-generated />
using System;
using DbUndervisning.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbUndervisning.Migrations
{
    [DbContext(typeof(WorldContext))]
    [Migration("20241118123106_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbUndervisning.Model.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassConstraint")
                        .HasColumnType("int");

                    b.Property<double>("Damage")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("HumanoidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("HumanoidId");

                    b.HasIndex("MobId");

                    b.ToTable("Abilities", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.NPCStuff.Humanoid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attackable")
                        .HasColumnType("bit");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Humanoids", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.NPCStuff.Mob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attackable")
                        .HasColumnType("bit");

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Mobs", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.Quests.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dialogue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HumanoidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemToCreateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HumanoidId")
                        .IsUnique();

                    b.HasIndex("ItemToCreateId");

                    b.ToTable("Quests", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.Quests.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Currency")
                        .HasColumnType("float");

                    b.Property<double>("Experience")
                        .HasColumnType("float");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .IsUnique();

                    b.ToTable("Rewards", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("placeholder siden jeg ikke har noget reelt asset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.Stat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Boost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("StatType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Stats", "DbUndervisningProject");
                });

            modelBuilder.Entity("DbUndervisning.Model.Ability", b =>
                {
                    b.HasOne("DbUndervisning.Model.NPCStuff.Humanoid", null)
                        .WithMany("Abilities")
                        .HasForeignKey("HumanoidId");

                    b.HasOne("DbUndervisning.Model.NPCStuff.Mob", null)
                        .WithMany("Abilities")
                        .HasForeignKey("MobId");
                });

            modelBuilder.Entity("DbUndervisning.Model.NPCStuff.Humanoid", b =>
                {
                    b.HasOne("DbUndervisning.Model.Region", null)
                        .WithMany("Humanoids")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("DbUndervisning.Model.NPCStuff.Mob", b =>
                {
                    b.HasOne("DbUndervisning.Model.Region", null)
                        .WithMany("Mobs")
                        .HasForeignKey("RegionId");
                });

            modelBuilder.Entity("DbUndervisning.Model.Quests.Quest", b =>
                {
                    b.HasOne("DbUndervisning.Model.NPCStuff.Humanoid", null)
                        .WithOne("Quest")
                        .HasForeignKey("DbUndervisning.Model.Quests.Quest", "HumanoidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbUndervisning.Model.Item", "ItemToCreate")
                        .WithMany()
                        .HasForeignKey("ItemToCreateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemToCreate");
                });

            modelBuilder.Entity("DbUndervisning.Model.Quests.Reward", b =>
                {
                    b.HasOne("DbUndervisning.Model.Quests.Quest", null)
                        .WithOne("Rewards")
                        .HasForeignKey("DbUndervisning.Model.Quests.Reward", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbUndervisning.Model.Stat", b =>
                {
                    b.HasOne("DbUndervisning.Model.Item", null)
                        .WithMany("Stats")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbUndervisning.Model.Item", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("DbUndervisning.Model.NPCStuff.Humanoid", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Quest")
                        .IsRequired();
                });

            modelBuilder.Entity("DbUndervisning.Model.NPCStuff.Mob", b =>
                {
                    b.Navigation("Abilities");
                });

            modelBuilder.Entity("DbUndervisning.Model.Quests.Quest", b =>
                {
                    b.Navigation("Rewards")
                        .IsRequired();
                });

            modelBuilder.Entity("DbUndervisning.Model.Region", b =>
                {
                    b.Navigation("Humanoids");

                    b.Navigation("Mobs");
                });
#pragma warning restore 612, 618
        }
    }
}
